---
title: "precipitation"
output: html_document
date: "2024-05-09"
---

```{r}
library("tidymodels")
library("data.table")
library("report")
library("gridExtra")
library("extremogram")
library("doParallel")
source("utils.R")
source("metrics.R")

set.seed(1234)
```

```{r}
reanalysis <- fread('reanalysis_precipitation_training_data.csv') |> mutate(month = as.factor(getMonth(time)),
                                                                      hour = as.factor(getHour(time)))
temp <- reanalysis |> 
    mutate(date = getDate(time)) |> 
    group_by(date) |> summarize(pr_daily = mean(pr_daily)) |> 
    mutate(pr_prev_daily = lag(pr_daily), pr_next_daily = lead(pr_daily)) |>
    select(-pr_daily) |>
    na.omit()

reanalysis <- reanalysis |> mutate(date = getDate(time)) |> inner_join(temp) |> select(-date)
rm(temp)
```

```{r}
temp_1 <- fread('reanalysis_tas_training_data.csv') |> 
          mutate(date = getDate(time)) |>
          group_by(date) |>
          summarize(tas_max_daily = max(tas), tas_min_daily = min(tas))

temperature <- fread('reanalysis_tas_training_data.csv') |> 
          mutate(date = getDate(time)) |>
          inner_join(temp_1, by=join_by(date)) |> select(-c(date,tas))

wind <- fread('reanalysis_sfcWind_training_data.csv') |> select(-sfcWind)

surface_pressure <- fread('reanalysis_surface_pressure_training_data.csv') |> select(-sp) |> mutate(sp_daily = sp_daily/100)

reanalysis <- reanalysis |> inner_join(temperature) |> inner_join(surface_pressure) |> inner_join(wind)
rm(wind, temp_1, temperature, surface_pressure)
```


```{r}
reanalysis_train <- reanalysis |> filter(time < as.Date('2014-01-01'))
reanalysis_test <- reanalysis |> filter(time >= as.Date('2014-01-01'))

reanalysis_reduced_train <- reanalysis_train |> select(-c(sfcWind_daily,sp_daily,sfcWind_daily,tas_max_daily,tas_min_daily))
reanalysis_reduced_test <- reanalysis_test |> select(-c(sfcWind_daily,sp_daily,sfcWind_daily,tas_max_daily,tas_min_daily))
```

```{r define_model, message=FALSE}
nv_recipe <- recipe(pr ~ ., data = reanalysis_train) |>
                update_role(time, new_role = "ID") |>
                step_interact(~ hour:pr_daily)

nv_model <- linear_reg() %>% set_engine("lm")

nv_workflow <- 
  workflow() %>% 
  add_model(nv_model) %>% 
  add_recipe(nv_recipe)

nv_fit <- fit(nv_workflow, reanalysis_train)

nv_pred <- predict(nv_fit, reanalysis_test)
rm(nv_recipe, nv_model, nv_workflow)
```

```{r}
xgb_recipe <- recipe(pr ~ ., data = reanalysis_train) |>
                update_role(time, new_role = "ID") |>
                step_dummy(all_nominal()) 
                
xgb_model <- boost_tree(
  trees = 1000,
  tree_depth = tune(), min_n = tune(),
  loss_reduction = tune(),                     ## first three: model complexity
  sample_size = tune(), mtry = tune(),         ## randomness
  learn_rate = tune()                          ## step size
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

xgb_wf <- workflow() %>%
  add_recipe(xgb_recipe) %>%
  add_model(xgb_model)

xgb_grid <- grid_latin_hypercube(
  tree_depth(),
  min_n(),
  loss_reduction(),
  sample_size = sample_prop(),
  finalize(mtry(), reanalysis_train),
  learn_rate(),
  size = 20
)

xgb_folds <- vfold_cv(reanalysis_train)

cl <- makeCluster(4)
registerDoParallel(cl)

xgb_tune_res <- tune_grid(
  xgb_wf,
  resamples = xgb_folds,
  grid = xgb_grid,
  control = control_grid(save_pred = TRUE)
)


### USE THE BEST XGBOOST
xgb_best <- select_best(xgb_tune_res, "rmse")

xgb_workflow <- xgb_wf |> finalize_workflow(xgb_best)

xgb_fit <- fit(xgb_workflow, reanalysis_train)

xgb_predicted <- predict(xgb_fit, reanalysis_test)

rm(xgb_wf, xgb_recipe, xgb_model, xgb_tune_res, xgb_folds, xgb_grid)
```

```{r show_summary, echo=FALSE}
engine <- extract_fit_engine(nv_fit)
#Hours are statistically significant, as is their interaction with the avg_sfcWinderature; months are not. 
engine |> report_table()
```

```{r, echo=FALSE}
res <-  reanalysis_test |> rename("obs_pr" = "pr") |>
  cbind(nv_pred) |> rename("nv_pr" = ".pred") |>
  cbind(xgb_predicted) |> rename("xgb_pr" = ".pred") |>
  select(c(time, obs_pr, nv_pr, xgb_pr))

lstm_predicted <- fread('lstm_output_pr.csv') 

res <- res |> slice(6:nrow(res)) |> 
   cbind(lstm_predicted) |> rename("lstm_pr" = "V1") |>
  filter(time >= as.Date('2014-01-02'))
```

```{r show_plot, echo=FALSE}
res_to_plot <- res[0:72,] 

p1 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_pr)) +
  geom_line(aes(y=nv_pr), color = "red") + 
  labs(y = "pr", x = "", title = "naive model")
  

p2 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_pr)) +
  geom_line(aes(y=xgb_pr), color = "red") + 
  labs(y = "pr", x = "", title = "xgboost model ")

p3 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_pr)) +
  geom_line(aes(y=lstm_pr), color = "red") + 
  labs(y = "pr", x = "", title = "lstm model ")

grid.arrange(p1, p2, p3, nrow = 2)
```

```{r, warning=FALSE}
r <- rbind(
        metrics(res$time, res$obs_pr, res$nv_pr, "nv"),
        metrics(res$time, res$obs_pr, res$xgb_pr, "xgb"),
        metrics(res$time, res$obs_pr, res$lstm_pr, "lstm_pr")
    )
r
```


```{r, warning=FALSE}
r <- rbind(
        metrics_2(res$time, res$obs_pr, res$nv_pr, "nv"),
        metrics_2(res$time, res$obs_pr, res$xgb_pr, "xgb"),
        metrics_2(res$time, res$obs_pr, res$lstm_pr, "lstm_pr")
    )
r
```

```{r}
res_rainy_days <- res |> filter(obs_pr >= 1)

r <- rbind(
        metrics(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$nv_pr, "nv"),
        metrics(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$xgb_pr, "xgb"),
        metrics(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$lstm_pr, "lstm_pr")
)
r
```
```{r}
r <- rbind(
        metrics_2(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$nv_pr, "nv"),
        metrics_2(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$xgb_pr, "xgb"),
        metrics_2(res_rainy_days$time, res_rainy_days$obs_pr, res_rainy_days$lstm_pr, "lstm_pr")
    )
r
```



```{r}
res_to_plot <- res |> 
    pivot_longer(
     cols = ends_with("_pr"),
     names_to = "model",
     names_pattern = "(.*)_pr",
     values_to = "pr",
     values_drop_na = TRUE
    ) 
  
ggplot(res_to_plot, aes(x=pr, color = model))+
  geom_density()
```

```{r}
res_to_plot <- res_rainy_days |> 
    pivot_longer(
     cols = ends_with("_pr"),
     names_to = "model",
     names_pattern = "(.*)_pr",
     values_to = "pr",
     values_drop_na = TRUE
    ) 
  
ggplot(res_to_plot, aes(x=pr, color = model)) +
  geom_density() +
  labs(title = "Precipitation on rainy days")
  
```

```{r}
# Function to create a Q-Q plot comparing quantiles of a sample column against a reference column
qq_plot_against <- function(data, sample_col) {
  ref_col <- "obs_pr"
  sample_data <- data[[sample_col]]
  ref_data <- data[[ref_col]]
  
  # Sort the data
  sample_data_sorted <- sort(sample_data)
  ref_data_sorted <- sort(ref_data)
  
  # Calculate quantiles
  n <- min(length(sample_data_sorted), length(ref_data_sorted))
  quantiles_sample <- sample_data_sorted[seq(1, length(sample_data_sorted), length.out = n)]
  quantiles_ref <- ref_data_sorted[seq(1, length(ref_data_sorted), length.out = n)]
  
  # Create a data frame for plotting
  quantile_df <- data.frame(Quantiles_Ref = quantiles_ref, Quantiles_Sample = quantiles_sample)
  
  # Generate the Q-Q plot
  ggplot(quantile_df, aes(x = Quantiles_Ref, y = Quantiles_Sample)) +
    geom_point() +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    ggtitle(paste("Q-Q Plot of", sample_col, "against", ref_col)) +
    xlab(paste("Quantiles of", ref_col)) +
    ylab(paste("Quantiles of", sample_col)) +
    theme_minimal()
}

# Columns to compare against the reference column
columns <- c("nv_pr", "xgb_pr", "lstm_pr")

# Generate Q-Q plots
plots <- lapply(columns, function(col) qq_plot_against(res, col))

# Arrange the plots using gridExtra
do.call(grid.arrange, c(plots, ncol = 2))  # Arrange in a grid
```

```{r}
res_to_plot <- res |> select(-time) |>
                      pivot_longer(cols = -obs_pr, names_to = "variable", values_to = "value")

ggplot(res_to_plot, aes(x = obs_pr, y = value)) +
  geom_point() +
  facet_wrap(~ variable) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
  theme_minimal() +
  labs(x = "Observed", y = "Predicted")
```

```{r}
p1 <- extremogram1(res$obs_pr, quant = .97, maxlag = 48, type = 1, ploting = 0)
p2 <- extremogram1(res$nv_pr, quant = .97, maxlag = 48, type = 1,  ploting = 0)
p3 <- extremogram1(res$xgb_pr, quant = .97, maxlag = 48, type = 1,  ploting = 0)
p4 <- extremogram1(res$lstm_pr, quant = .97, maxlag = 48, type = 1,  ploting = 0)

res_to_plot <- data.frame(model = c(rep("obs", 48), rep("nv", 48), rep("xgboost", 48), rep("lstm",48)),
                          lag = c(1:48, 1:48, 1:48, 1:48),
                          extremogram = c(p1,p2,p3,p4))

ggplot(res_to_plot, mapping = aes(x = lag, y = extremogram)) +
    geom_segment(mapping = aes(xend = lag, yend = 0)) +
    facet_wrap(~ model, nrow = 2)
```

```{r}
p1 <- acf(res$obs_pr, lag.max = 47, plot = F)
p2 <- acf(res$nv_pr, lag.max = 47, plot = F)
p3 <- acf(res$xgb_pr, lag.max = 47, plot = F)
p4 <- acf(res$lstm_pr, lag.max = 47, plot = F)

res_to_plot <- data.frame(model = c(rep("obs", 48), rep("nv", 48), rep("xgboost", 48), rep("lstm", 48)),
                          lag = c(1:48, 1:48, 1:48, 1:48),
                          acf = c(p1$acf,p2$acf,p3$acf,p4$acf))

ggplot(res_to_plot, mapping = aes(x = lag, y = acf)) +
    geom_segment(mapping = aes(xend = lag, yend = 0)) +
    facet_wrap(~ model, nrow = 2)
```
