---
title: "v2_wind_model"
output: html_document
date: "2024-05-07"
---

```{r load_packages, results='hide', message=FALSE}
library("tidymodels")
library("data.table")
library("report")
library("gridExtra")
library("extremogram")
source("utils.R")
source("metrics.R")

reanalysis <- fread('reanalysis_sfcWind_training_data.csv') 
cmip_6 <- fread('cmip6_sfcWind_to_downscale_data.csv') 
```

### Preparate the data for the naive model v2.0

```{r}
temp <- reanalysis |> mutate(date = getDate(time)) |> 
    group_by(date) |> summarize(avg_sfcWind = mean(avg_sfcWind)) |> 
    mutate(prev_avg_sfcWind = lag(avg_sfcWind), nxt_avg_sfcWind = lead(avg_sfcWind)) |>
    select(-avg_sfcWind) |>
    na.omit()
reanalysis_v2 <- reanalysis |> mutate(date = getDate(time)) |> inner_join(temp) |> select(-date)
rm(temp)

temp <- cmip_6 |> mutate(date = getDate(time)) |> 
    group_by(date) |> summarize(avg_sfcWind = mean(avg_sfcWind)) |> 
    mutate(prev_avg_sfcWind = lag(avg_sfcWind), nxt_avg_sfcWind = lead(avg_sfcWind)) |>
    select(-avg_sfcWind) |>
    na.omit()
cmip_6_v2 <- cmip_6 |> mutate(date = getDate(time)) |> inner_join(temp) |> select(-date)
rm(temp)
```

```{r}
reanalysis_train <- reanalysis |> filter(time < as.Date('2014-01-01'))
reanalysis_test <- reanalysis |> filter(time >= as.Date('2014-01-01'))

reanalysis_v2_train <- reanalysis_v2 |> filter(time < as.Date('2014-01-01'))
reanalysis_v2_test  <- reanalysis_v2 |> filter(time >= as.Date('2014-01-01'))
```

```{r define_model, message=FALSE}
model_recipe <- recipe(sfcWind ~ ., data = reanalysis_train) |>
                update_role(time, new_role = "ID") |>
                step_mutate(hour = as.factor(getHour(time)), month = as.factor(getMonth(time))) |>
                step_dummy(all_integer()) |>
                step_interact(~ hour:avg_sfcWind)

model <- linear_reg() %>% set_engine("lm")

model_workflow <- 
  workflow() %>% 
  add_model(model) %>% 
  add_recipe(model_recipe)

model_fit <- fit(model_workflow, reanalysis_train)

predicted <- predict(model_fit, reanalysis_test)
```


```{r naive_model_2, message=FALSE}
model_recipe_v2 <- recipe(sfcWind ~ ., data = reanalysis_v2_train) |>
                update_role(time, new_role = "ID") |>
                step_mutate(hour = as.factor(getHour(time)), month = as.factor(getMonth(time))) |>
                step_dummy(all_integer()) |>
                step_interact(~ hour:avg_sfcWind + hour:nxt_avg_sfcWind + hour:prev_avg_sfcWind)


model_v2 <- linear_reg() %>% set_engine("lm")

model_workflow_v2 <- 
  workflow() %>% 
  add_model(model_v2) %>% 
  add_recipe(model_recipe_v2)

model_fit_v2 <- fit(model_workflow_v2, reanalysis_v2_train)


predicted_v2 <- reanalysis_v2_test |> cbind(predict(model_fit_v2, reanalysis_v2_test)) |> select(time,.pred)
```


```{r}
knnreg <- copy(reanalysis_train) |> filter(time = NA) |> select(-avg_sfcWind) #Copy dataframe for structure

for(i in 0:23){
  train <- reanalysis_train |> filter(getHour(time) == i)
  test <- reanalysis_test |> filter(getHour(time) == i)


  knnreg_recipe <- recipe(sfcWind ~ avg_sfcWind, data = train) |>
    step_scale(all_predictors()) |>
    step_center(all_predictors())

  knnreg_model <- nearest_neighbor(weight_func = "rectangular",
                                neighbors = 10) |>
                                set_engine("kknn") |>
                                set_mode("regression")

  knnreg_wkflw <- workflow() |>
    add_recipe(knnreg_recipe) |>
    add_model(knnreg_model)
  
  knnreg_fit <- fit(knnreg_wkflw, train)
  
  test$sfcWind <- knnreg_fit |>
                        predict(test)
  test <- test |> select(-avg_sfcWind)
  knnreg <- knnreg |> bind_rows(test)
  
}
rm(test)
knnreg <- knnreg |> rename("knnreg_sfcWind" = "sfcWind") |> arrange(time)
```


```{r show_plot, echo=FALSE}
res_to_plot <- res[0:72,] 

p1 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_sfcWind)) +
  geom_line(aes(y=nv_sfcWind), color = "red") + 
  labs(y = "sfcWind", x = "", title = "naive model")


p3 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_sfcWind)) +
  geom_line(aes(y=nv2_sfcWind), color = "red") + 
  labs(y = "sfcWind", x = "", title = "naive 2.0 model ")

p4 <- ggplot(res_to_plot, aes(x=time)) +
  geom_line(aes(y=obs_sfcWind)) +
  geom_line(aes(y=knnreg_sfcWind), color = "red") + 
  labs(y = "sfcWind", x = "", title = "knn regression model")

grid.arrange(p1, p3, p4, nrow = 2)
```


```{r}
res <- reanalysis_test |> 
        cbind(predicted) |> 
        rename("obs_sfcWind" = "sfcWind", "nv_sfcWind"  = ".pred") |>
        inner_join(predicted_v2) |>
        rename("nv2_sfcWind" = ".pred") |>
        inner_join(knnreg)
```

```{r}
r <- rbind(
        metrics(res$time, res$obs_sfcWind, res$nv_sfcWind, "nv"),
        metrics(res$time, res$obs_sfcWind, res$nv2_sfcWind, "nv_2"),
        metrics(res$time, res$obs_sfcWind, res$knnreg_sfcWind, "knnreg")
      )
```

```{r}
res_to_plot <- res |> 
    select(!ends_with("avg_sfcWind")) |>
    pivot_longer(
     cols = ends_with("_sfcWind"),
     names_to = "model",
     names_pattern = "(.*)_sfcWind",
     values_to = "sfcWind",
     values_drop_na = TRUE
    ) 
  
ggplot(res_to_plot, aes(x=sfcWind, color = model))+
  geom_density()
```

```{r}
p1 <- maximum_histograms(res$time, res$obs_sfcWind, res$nv_sfcWind) + scale_fill_discrete(labels = c("nv", "obs"))
p2 <- maximum_histograms(res$time, res$obs_sfcWind, res$knnreg_sfcWind) + scale_fill_discrete(labels = c("knnr", "obs"))
p3 <- maximum_histograms(res$time, res$obs_sfcWind, res$nv2_sfcWind) + scale_fill_discrete(labels = c("nv2", "obs"))

grid.arrange(p1, p2, p3,  nrow = 3, top = "How Often Peaks Hit Hourly")
```
```{r}
p1 <- extremogram1(res$obs_sfcWind, quant = .97, maxlag = 48, type = 1, ploting = 0)
p2 <- extremogram1(res$nv_sfcWind, quant = .97, maxlag = 48, type = 1, ploting = 0)
p3 <- extremogram1(res$nv2_sfcWind, quant = .97, maxlag = 48, type = 1,  ploting = 0)
p4 <- extremogram1(res$knnreg_sfcWind, quant = .97, maxlag = 48, type = 1,  ploting = 0)

res_to_plot <- data.frame(model = c(rep("obs", 48), rep("knnr", 48), rep("nv2", 48), rep("knnreg", 48)),
                          lag = c(1:48, 1:48, 1:48, 1:48),
                          extremogram = c(p1,p2,p3,p4))

ggplot(res_to_plot, mapping = aes(x = lag, y = extremogram)) +
    geom_segment(mapping = aes(xend = lag, yend = 0)) +
    facet_wrap(~ model, nrow = 2)
```

```{r}
p1 <- acf(res$obs_sfcWind,  lag.max = 47, plot = F)
p2 <- acf(res$nv_sfcWind,  lag.max = 47, plot = F)
p3 <- acf(res$nv2_sfcWind, lag.max = 47, plot = F)
p4 <- acf(res$knnreg_sfcWind, lag.max = 47, plot = F)

res_to_plot <- data.frame(model = c(rep("obs", 48), rep("nv", 48), rep("nv2", 48), rep("knnreg", 48)),
                          lag = c(1:48, 1:48, 1:48, 1:48),
                          acf = c(p1$acf,p2$acf,p3$acf,p4$acf))

ggplot(res_to_plot, mapping = aes(x = lag, y = acf)) +
    geom_segment(mapping = aes(xend = lag, yend = 0)) +
    facet_wrap(~ model, nrow = 2)
```


