---
title: "Downscaling estadístico de proyecciones climáticas"
date: "Noviembre 2024"
# date-format: long
author: Ignacio Alvarez-Castro
format: 
 beamer:
  colortheme: seahorse
  # theme: Szeged
  toc: false
lang: es
execute:
  echo: false
  warning: false
---

<<<<<<< HEAD
# Introducción

## Proyecto
*Cuantificación de incertidumbre e identificación de eventos extremos en escenarios de producción renovable generados.*
\vspace{1cm}

\begin{itemize}
\item Proyecto ANII - 173061: Fondo sectorial de energía 2022. 
\item Equipo de trabajo: Bruno Tancredi, Jairo Cugliari, Ignacio Alvarez-Castro
\end{itemize}
=======
## Introducción

-   Proyecto ANII-173061: Fondo sectorial de energía 2022. 

\begin{itemize}
\setlength\itemsep{.5cm}
\item Generación de energía proveniente de fuentes renovables es cada vez más importante.
\item Las fuentes renovables se basan en la transformación de *recursos primarios* 
\item Recursos primarios: lluvia, viento, radiación solar, temperatura. 
\item Modelar generación de energía nesecita series de recursos primarios horaria
\end{itemize}


## Objetivo

- Evaluación de modelos y escenarios climáticos relevantes

- Obtener series de recursos primarios a escala reducida

-  Evaluación de probabilidades de eventos extremos en recursos primarios.


# Datos

## Modelos climáticos CMIP6 

- Programa mundial para investigación en clima

- Escenarios combinan:      
      - Concentración gases: de 1.9 a 8.5
      
      - Trayectoria socioeconómica: 1 a 5 
    
- Simulaciones de principales variables a largo plazo

## Escenarios CMIP6

gráfico mostrando efecto de escenarios para un lab

## ERA5

\begin{itemize}
\setlength\itemsep{.5cm}
\item **Reanálisis atmosférico**: combina datos observados en estaciones meteorológicas, con modelo físico de circulación general de la atmósfera. 
\item Represantan la mejor estimación de las variables climáticas que se puede tener
\item Tiene mediciones horarias
\item **Datos Observados**: Reanálisis atmosférico ERA5. 
\end{itemize}

# Métodos

## Downscaling temportal

Con los datos observados (ERA5): definimos $y_{ih}$ la variable de interés para el día $i$ en la hora $h$. 

Consideramos el siguiente modelo lineal: 
$$ y_{ih} = \beta_0 + \beta_{1h} + \beta_2 y_{i.} + \beta_{3h}y_{i.} + \epsilon_i $$

Luego se puede obtener estimaciones como: 
\pause

$$ \hat{y_{ih}^k} = \hat\beta_0 + \hat\beta_{1h} + \hat\beta_2 y_i^k + \hat\beta_{3h}y_i^k$$

- $y_i^k$: es la variable de interés en el día $i$ proyectada por CMIP6 bajo escenario $k$. 

- $\hat{y_{ih}^k}$: variable de interés en escala horaria. 


## Modelos estimados

En general, 

$$
\begin{array}{cl}
y_{ih} = & f(y_{i.}, x_{i}) + \epsilon_i  \\ 
& \\ 
\hat{y_{ih}^k} = & \hat f(y_{i}^k, x_{i})
\end{array}
$$

- Obtener $\hat f(\cdot)$: naive (lineal), Redes (cnn, lstm), Árboles(xgboost)
- Variables explicativas: otras series de CMIP6, indicadoras de hora, horas de luz, etc


## Métodos evaluación

Crear conjunto entrenamiento y test en base a datos Re-Análisis. 

Métricas

- Errores absolutos, ratio varaibilidad, KGE

- Percentiles (qq-plot)

- Hora de ocurrencia del máximo

- Incremento/caída

- Dependencia: correlación, ACF, Extremograma

## Ressultados

-   Resultados de Temperatura ([enlace](https://rpubs.com/nachalca/tas))

-  Resultados Viento  ([enlace](https://rpubs.com/nachalca/viento))

- Resultados Lluvia ([enlace](https://rpubs.com/nachalca/lluvia))







